#!/usr/bin/env bash
# Regenerate requirements.lock / requirements-dev.lock inside the runtime base image.
set -euo pipefail

cd "$(dirname "$0")/.."

IMAGE="python:3.14-slim"

generate() {
    local extra="$1" outfile="$2" spec="."
    [[ -n "$extra" ]] && spec=".[${extra}]"

    echo "Resolving ${spec} -> ${outfile}"
    docker run --rm -v "$PWD:/src:ro" -w /tmp "$IMAGE" sh -c "
        set -e
        cp -r /src/pyproject.toml /src/template_service /tmp/
        mkdir -p /tmp/tests && touch /tmp/tests/__init__.py
        pip install --quiet --no-cache-dir '${spec}'
        pip freeze --exclude-editable
    " | grep -v '^template-service' > "$outfile.tmp"

    {
        echo "# Generated by scripts/lock.sh — do not edit by hand."
        echo "# Regenerate with: make lock"
        cat "$outfile.tmp"
    } > "$outfile"
    rm -f "$outfile.tmp"
}

generate "" requirements.lock
generate "dev" requirements-dev.lock

echo "Done."
